# Generated by Django 6.0.7 on 2026-07-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('exception', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
